version: '3.9'

services:
    runner:
        build:
            context: ./services/k6/
        user: root
        profiles:
            - test
        dns:
            - '8.8.8.8'
        env_file: .env
        environment:
            - REPORTS_PATH=/app/reports
            - K6_OUT=output-elasticsearch
            - K6_ELASTICSEARCH_URL=http://elasticsearch:9200
            - K6_ELASTICSEARCH_USER=elastic
            - K6_ELASTICSEARCH_PASSWORD=password
            - K6_ELASTICSEARCH_INSECURE_SKIP_VERIFY=false
        volumes:
            - ./tests/stress.js:/app/script.js
            - ./reports/:/app/reports
            - ./services/k6/entrypoint.sh:/app/entrypoint.sh
            - /run/docker.sock:/run/docker.sock
        entrypoint: /app/entrypoint.sh

    mockoon:
        build: ./services/mockoon
        profiles:
            - env
        ports:
            - '3000:3000'
        healthcheck:
            test: curl -u 'test:test' localhost:3000/api/token
            interval: 10s
            retries: 60
            start_period: 30s

    elasticsearch:
        image: elasticsearch:8.11.3
        profiles:
            - env
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - '9200:9200'
        healthcheck:
            test: curl -XGET 'localhost:9200/_cluster/health?pretty'
            interval: 10s
            retries: 60
            start_period: 30s

    kibana:
        image: kibana:8.11.3
        profiles:
            - env
        ports:
            - "5601:5601"
        depends_on:
            elasticsearch:
                condition: service_healthy
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        volumes:
            - ./services/kibana/k6-objects.ndjson:/app/k6-objects.ndjson
        healthcheck:
            test: "curl -X POST 'http://kibana:5601/api/saved_objects/_import?overwrite=true' -H 'kbn-xsrf: true' --form file=@/app/k6-objects.ndjson"
            interval: 10s
            retries: 60
            start_period: 30s
